import type { WispApi } from "../../shared/contracts";

const REQUIRED_WISP_METHODS = [
  "getPluginSettings",
  "savePluginSettings",
  "savePluginDefaults",
  "removePlugin",
  "testPluginConnection",
  "getWispPluginAccess",
  "saveWispPluginAccess",
  "getMcpSettings",
  "saveMcpServer",
  "removeMcpServer",
  "testMcpConnection",
  "refreshMcpTools",
  "startMcpSignIn",
  "cancelMcpSignIn",
  "getWispMcpAccess",
  "saveWispMcpAccess",
  "subscribeToMcpSettings",
  "startConversation",
  "sendMessage",
  "abortConversation",
  "applyModel",
  "getConversationModel",
  "manageContext",
  "disposeConversation",
  "subscribeToAgentEvents",
  "getAiSettings",
  "saveAiSettings",
  "removeProviderCredential",
  "getConversationState",
  "initializeConversations",
  "createConversation",
  "updateConversation",
  "deleteConversation",
  "appendConversationMessage",
  "answerConversationPrompt",
  "markConversationRead",
  "subscribeToConversationChanges",
  "getConversationMessages",
  "searchMessages",
  "getSessionReport",
  "getUsageReport",
  "getUserProfile",
  "saveUserProfile",
  "getToolPolicy",
  "saveToolPolicy",
  "resolveToolApproval",
  "getLaunchAtLoginState",
  "setLaunchAtLogin",
  "getUpdateState",
  "checkForUpdates",
  "downloadUpdate",
  "installUpdate",
  "openReleasesPage",
  "subscribeToUpdateState",
  "getWorkspace",
  "openWorkspaceFolder",
  "openSkillsFolder",
  "attachWorkspaceFiles",
  "listSkills",
  "deleteSkill",
  "getVoiceSettings",
  "saveVoiceCredential",
  "transcribeAudio",
  "getConnections",
  "saveConnection",
  "removeConnection",
  "activateConnection",
  "retryConnection",
  "installServer",
  "subscribeToConnections",
] as const satisfies ReadonlyArray<keyof WispApi>;

export function isWispBridgeAvailable(value: unknown): value is WispApi {
  if (!value || typeof value !== "object") return false;
  const candidate = value as Record<string, unknown>;
  return REQUIRED_WISP_METHODS.every((method) => typeof candidate[method] === "function");
}
